apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: rootProject.file('publish.gradle')

android {
    namespace 'com.opensource.svgaplayer.loader'
    compileSdk 35
    defaultConfig { minSdk 21; testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    kotlinOptions { jvmTarget = '17' }
}
dependencies {
    api project(':library')
    api 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
